export const ROUTER = {
  HOME: '/',
  SIGN_IN: '/sign-in',
  PRODUCT_MANAGEMENT: '/products',
  CREATE_PRODUCT: '/products/create',
  EDIT_PRODUCT: '/products/:id/edit',
  CATEGORY_MANAGEMENT: '/categories',
  BRAND_MANAGEMENT: '/brands',
  ORDER_MANAGEMENT: '/orders',
  BANNERS_MANAGEMENT: '/banners',
  USER_MANAGEMENT: '/users',
  ADMIN_MANAGEMENT: '/admins',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  VOUCHER_MANAGEMENT: '/vouchers',
} as const;
